const TOTAL_DAYS=80;
const START_DATE='2026-08-13';
const KEY='eighty-days-of-bok-records';
const MISSION_KEY='eighty-days-of-bok-missions';
const encouragements=[['첫 걸음을<br>응원해요','완벽하지 않아도 괜찮아요.<br>시작한 마음 자체가 이미 복입니다.'],['오늘의 정성이<br>빛나고 있어요','짧은 실천도 괜찮아요.<br>쌓인 마음은 분명 나를 바꿔요.'],['참 잘하고<br>있어요','두 가지를 해낸 오늘,<br>꾸준한 내가 정말 대단해요.'],['오늘은 팡파레예요!','신·행·학 세 가지를 모두 해냈어요.<br>나를 마음껏 칭찬해 주세요 🎉']];
const records=JSON.parse(localStorage.getItem(KEY)||'{}');
const missions=JSON.parse(localStorage.getItem(MISSION_KEY)||'{}');
const dayGrid=document.querySelector('#dayGrid');
const pad=n=>String(n).padStart(2,'0');
function dateForDay(day){const d=new Date(`${START_DATE}T00:00:00`);d.setDate(d.getDate()+day-1);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function shortDate(day){const d=dateForDay(day).split('-');return `${Number(d[1])}/${Number(d[2])}`}
function categoryCount(r){if(!r)return 0;let count=0;if(Number(r.sin||r.hours)>0)count++;if(String(r.haeng||'').trim())count++;if(Number(r.hak)>0)count++;return count}
function hasRecord(r){return categoryCount(r)>0}
function getDoneDays(){return Object.keys(records).filter(k=>hasRecord(records[k])).map(Number).sort((a,b)=>a-b)}
function localDateKey(date=new Date()){return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`}
function getTodayDay(){const start=new Date(`${START_DATE}T00:00:00`);const now=new Date(`${localDateKey()}T00:00:00`);return Math.max(1,Math.min(TOTAL_DAYS,Math.floor((now-start)/86400000)+1))}
function getCurrentDay(){return getTodayDay()}
function badgeFor(r){const count=categoryCount(r);return count===3?'🎉':'🪷'.repeat(count)}
function renderGrid(){dayGrid.innerHTML='';const today=new Date().toISOString().slice(0,10);for(let i=1;i<=TOTAL_DAYS;i++){const r=records[i];const el=document.createElement('div');el.className='day-cell';if(hasRecord(r))el.classList.add('done');if(dateForDay(i)===today||i===getCurrentDay())el.classList.add('today');el.innerHTML=`<strong>DAY ${pad(i)}</strong><span class="day-date">${shortDate(i)}</span><span class="day-badge">${badgeFor(r)||'·'}</span>`;dayGrid.appendChild(el)}}
function updateStats(){const done=getDoneDays();const total=done.reduce((sum,d)=>sum+Number(records[d].sin||records[d].hours||0),0);const pct=Math.round(done.length/TOTAL_DAYS*100);document.querySelector('#daysDone').textContent=done.length;document.querySelector('#totalHours').textContent=total%1?total.toFixed(1):total;document.querySelector('#progressPercent').textContent=pct;document.querySelector('#progressBar').style.width=pct+'%';document.querySelector('#completedLabel').textContent=`${done.length} / 80일 완료`;document.querySelector('#sealCount').textContent=`${done.length}개 모음`;let streak=0,expected=done.length?done[done.length-1]:0;for(let i=done.length-1;i>=0&&done[i]===expected;i--){streak++;expected--}document.querySelector('#streakDays').textContent=streak;const day=getCurrentDay();document.querySelector('#heroDay').textContent=pad(day);document.querySelector('#encouragementDay').textContent='DAY '+pad(day);const msg=encouragements[Math.min(Math.max(categoryCount(records[day])-1,0),3)];document.querySelector('#encouragementTitle').innerHTML=msg[0];document.querySelector('#encouragementText').innerHTML=msg[1];document.querySelectorAll('.milestone').forEach(el=>el.classList.toggle('reached',done.length>=Number(el.dataset.day)));if(done.length>=75){document.querySelector('#final h2').innerHTML='75일의 여정이<br><em>완성되었어요.</em>';document.querySelector('#final p').innerHTML=`신·행·학을 기록한 ${done.length}일의 실천을 만들었어요.<br>이 기록은 앞으로의 나를 비추는 복이 됩니다.`}}
function renderMilestones(){const items=[[15,'습관의 씨앗','작은 실천이 일상에 자리 잡기 시작해요.'],[35,'마음의 변화','내가 달라진 순간을 찾아보세요.'],[55,'깊어지는 정성','여기까지 온 나를 마음껏 칭찬해 주세요.'],[75,'나만의 결과','75일의 기록이 나만의 변화로 완성돼요.']];document.querySelector('#milestoneList').innerHTML=items.map(x=>`<div class="milestone" data-day="${x[0]}"><div class="milestone-day">DAY ${x[0]}</div><p><b>${x[1]}</b><br>${x[2]}</p>${x[0]===15?'<div class="reward-mission">☕ <span>15일 완수 선물</span><strong>나에게 맛있는 음료 사주기</strong></div>':''}</div>`).join('')}
function renderMissions(){const done=Object.values(missions).filter(Boolean).length;document.querySelector('#missionStampCount').textContent=`${done}/4`;document.querySelector('#songpyeonTray').querySelectorAll('.earned-songpyeon').forEach(el=>el.remove());document.querySelectorAll('.mission-item').forEach(item=>{const key=item.dataset.mission;const checked=Boolean(missions[key]);const available=localDateKey()>=key;item.classList.toggle('completed',checked);item.classList.toggle('locked',!available);const button=item.querySelector('.mission-check');button.disabled=!available;button.textContent=checked?'완료됨 ✓':available?'체크하기':'9/24부터 가능';if(checked){const stamp=document.createElement('span');stamp.className='earned-songpyeon';stamp.textContent='🥮';stamp.title=`${key} 송편 도장`;document.querySelector('#songpyeonTray').appendChild(stamp)}})}
function setDate(){const d=new Date();document.querySelector('#todayDate').textContent=`${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())}`}
document.querySelector('#recordForm').addEventListener('submit',e=>{e.preventDefault();const day=getCurrentDay();const sin=Number(document.querySelector('#practiceSin').value)||0;const haeng=document.querySelector('#practiceHaeng').value.trim();const hak=Number(document.querySelector('#practiceHak').value)||0;if(!sin&&!haeng&&!hak){showToast('신·행·학 중 하나 이상 기록해 주세요.');return}records[day]={hours:sin,sin,haeng,hak,note:document.querySelector('#practiceNote').value,date:dateForDay(day)};localStorage.setItem(KEY,JSON.stringify(records));document.querySelector('#savedState').hidden=false;document.querySelector('#recordForm').reset();renderGrid();updateStats();showToast(categoryCount(records[day])===3?'🎉 팡파레! 오늘은 세 가지 모두 완료했어요!':`🪷 복운도장 ${categoryCount(records[day])}개가 찍혔어요!`)});
document.querySelectorAll('.mission-check').forEach(button=>button.addEventListener('click',()=>{const key=button.closest('.mission-item').dataset.mission;missions[key]=!missions[key];localStorage.setItem(MISSION_KEY,JSON.stringify(missions));renderMissions();showToast(missions[key]?'🥮 송편 도장이 찍혔어요!':'송편 도장을 다시 비웠어요.')}));
document.querySelector('#resetBtn').addEventListener('click',()=>{if(confirm('모든 기록을 지우고 새로 시작할까요?')){localStorage.removeItem(KEY);localStorage.removeItem(MISSION_KEY);location.reload()}});function showToast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}renderMilestones();setDate();renderGrid();updateStats();renderMissions();
